import type { FileCategory } from './categories'

export const EXTENSION_CATEGORY_MAP: Record<string, FileCategory> = {
  // Images
  jpg: 'images',
  jpeg: 'images',
  png: 'images',
  gif: 'images',
  bmp: 'images',
  webp: 'images',
  svg: 'images',
  ico: 'images',
  tif: 'images',
  tiff: 'images',
  heic: 'images',
  heif: 'images',
  avif: 'images',
  jxl: 'images',
  apng: 'images',
  raw: 'images',
  cr2: 'images',
  cr3: 'images',
  nef: 'images',
  arw: 'images',
  dng: 'images',
  psd: 'images',
  ai: 'images',
  eps: 'images',
  xcf: 'images',

  // Videos
  mp4: 'videos',
  mkv: 'videos',
  avi: 'videos',
  mov: 'videos',
  wmv: 'videos',
  flv: 'videos',
  webm: 'videos',
  m4v: 'videos',
  mpg: 'videos',
  mpeg: 'videos',
  '3gp': 'videos',
  '3g2': 'videos',
  m2ts: 'videos',
  mts: 'videos',
  vob: 'videos',
  ogv: 'videos',
  m2v: 'videos',

  // Audio
  mp3: 'audio',
  wav: 'audio',
  flac: 'audio',
  aac: 'audio',
  ogg: 'audio',
  oga: 'audio',
  opus: 'audio',
  m4a: 'audio',
  wma: 'audio',
  aiff: 'audio',
  aif: 'audio',
  mid: 'audio',
  midi: 'audio',
  amr: 'audio',
  mka: 'audio',
  wv: 'audio',
  ape: 'audio',

  // Documents
  pdf: 'documents',
  doc: 'documents',
  docx: 'documents',
  xls: 'documents',
  xlsx: 'documents',
  ppt: 'documents',
  pptx: 'documents',
  odt: 'documents',
  ods: 'documents',
  odp: 'documents',
  txt: 'documents',
  rtf: 'documents',
  md: 'documents',
  markdown: 'documents',
  csv: 'documents',
  tsv: 'documents',
  epub: 'documents',
  mobi: 'documents',
  azw3: 'documents',
  tex: 'documents',
  pages: 'documents',
  numbers: 'documents',
  keynote: 'documents',
  docm: 'documents',
  xlsm: 'documents',
  pptm: 'documents',
  dotx: 'documents',
  potx: 'documents',
  msg: 'documents',
  eml: 'documents',
  wps: 'documents',

  // Archives
  zip: 'archives',
  rar: 'archives',
  '7z': 'archives',
  tar: 'archives',
  gz: 'archives',
  bz2: 'archives',
  xz: 'archives',
  zst: 'archives',
  zstd: 'archives',
  lz: 'archives',
  lzma: 'archives',
  tgz: 'archives',
  tbz2: 'archives',
  txz: 'archives',
  arj: 'archives',
  ace: 'archives',
  cab: 'archives',
  jar: 'archives',
  war: 'archives',
  iso: 'archives',
  img: 'archives',
  cbz: 'archives',
  cbr: 'archives',
  zipx: 'archives',

  // Installers
  exe: 'installers',
  msi: 'installers',
  msix: 'installers',
  appx: 'installers',
  pkg: 'installers',
  appimage: 'installers',
  deb: 'installers',
  rpm: 'installers',
  apk: 'installers',
  dmg: 'installers',
  flatpak: 'installers',
  snap: 'installers',
  bundle: 'installers',
  nupkg: 'installers',

  // Code
  ts: 'code',
  tsx: 'code',
  js: 'code',
  jsx: 'code',
  mjs: 'code',
  cjs: 'code',
  py: 'code',
  pyw: 'code',
  ipynb: 'code',
  rb: 'code',
  php: 'code',
  java: 'code',
  kt: 'code',
  kts: 'code',
  scala: 'code',
  go: 'code',
  rs: 'code',
  c: 'code',
  h: 'code',
  cpp: 'code',
  hpp: 'code',
  cc: 'code',
  cxx: 'code',
  cs: 'code',
  fs: 'code',
  swift: 'code',
  m: 'code',
  mm: 'code',
  dart: 'code',
  lua: 'code',
  pl: 'code',
  pm: 'code',
  r: 'code',
  sh: 'code',
  bash: 'code',
  zsh: 'code',
  fish: 'code',
  bat: 'code',
  cmd: 'code',
  ps1: 'code',
  psd1: 'code',
  psm1: 'code',
  vbs: 'code',
  sql: 'code',
  json: 'code',
  yaml: 'code',
  yml: 'code',
  xml: 'code',
  toml: 'code',
  ini: 'code',
  cfg: 'code',
  conf: 'code',
  properties: 'code',
  vue: 'code',
  svelte: 'code',
  html: 'code',
  htm: 'code',
  css: 'code',
  scss: 'code',
  less: 'code',
  styl: 'code',
  elm: 'code',
  ex: 'code',
  exs: 'code',
  clj: 'code',
  cljs: 'code',
  edn: 'code',
  hs: 'code',
  erl: 'code',
  erln: 'code',
  tcl: 'code',
  jl: 'code',
  nim: 'code',
  zig: 'code',
  v: 'code',
  groovy: 'code',
  gradle: 'code',
  tf: 'code',
  hcl: 'code',
  dockerfile: 'code',
  makefile: 'code',

  // Projects
  sln: 'projects',
  csproj: 'projects',
  fsproj: 'projects',
  vcxproj: 'projects',
  xcodeproj: 'projects',
  pbxproj: 'projects',
  workspace: 'projects',
  project: 'projects',
  vim: 'projects',
  godot: 'projects',
  uproject: 'projects',
  uplugin: 'projects',
  unitypackage: 'projects',

  // Fonts
  ttf: 'fonts',
  otf: 'fonts',
  woff: 'fonts',
  woff2: 'fonts',
  eot: 'fonts',
  ttc: 'fonts',
  otc: 'fonts',
  dfont: 'fonts',

  // Databases
  db: 'databases',
  sqlite: 'databases',
  sqlite3: 'databases',
  db3: 'databases',
  sqlitedb: 'databases',
  mdb: 'databases',
  accdb: 'databases',
  dbf: 'databases',
  frm: 'databases',
  myd: 'databases',
  myi: 'databases',
  ndb: 'databases',
  ldb: 'databases',

  // Backups
  bak: 'backups',
  backup: 'backups',
  old: 'backups',
  orig: 'backups',
  sbk: 'backups',
  bkp: 'backups',

  // Temporary
  tmp: 'temporary',
  temp: 'temporary',
  part: 'temporary',
  crdownload: 'temporary',
  download: 'temporary',
  cache: 'temporary',
  swp: 'temporary',
  swo: 'temporary',
  lock: 'temporary',
  pid: 'temporary',
  log: 'temporary',
}

/**
 * Returns the lowercase extension of a file name (without the dot),
 * or null when the name has no extension. Dotfiles such as `.env`
 * are treated as extension-less.
 */
export function extensionOf(name: string): string | null {
  const base = name.trim()
  if (base.length === 0 || base === '.' || base === '..') return null
  const lastDot = base.lastIndexOf('.')
  if (lastDot <= 0) return null
  const ext = base.slice(lastDot + 1)
  if (ext.length === 0 || ext.includes('/') || ext.includes('\\')) return null
  return ext.toLowerCase()
}

export function categoryForExtension(extension: string): FileCategory | null {
  return EXTENSION_CATEGORY_MAP[extension.toLowerCase()] ?? null
}

/** Well-known OS-generated junk files, classified as temporary. */
export const JUNK_FILE_NAMES = new Set(['desktop.ini', 'thumbs.db', '.ds_store', 'thumbs.db:encryptable'])

/** Hidden dotfiles that are clearly configuration, classified as code. */
export const HIDDEN_CONFIG_FILES = new Set([
  '.gitignore',
  '.gitattributes',
  '.gitmodules',
  '.npmrc',
  '.yarnrc',
  '.nvmrc',
  '.babelrc',
  '.eslintrc',
  '.eslintrc.json',
  '.eslintrc.js',
  '.prettierrc',
  '.prettierrc.json',
  '.editorconfig',
  '.dockerignore',
  '.env',
  '.env.example',
  '.env.local',
  '.stylelintrc',
  '.browserslistrc',
  '.npmignore',
  '.terraformrc',
  '.gitconfig',
  '.htaccess',
])

/** Well-known filenames without extensions that are source/build files. */
export const CODE_FILE_NAMES = new Set([
  'dockerfile',
  'containerfile',
  'makefile',
  'rakefile',
  'gemfile',
  'procfile',
  'vagrantfile',
  'jenkinsfile',
  'justfile',
  'taskfile',
  'cmakelists.txt',
])

/** Well-known filenames without extensions that are documents. */
export const DOCUMENT_FILE_NAMES = new Set([
  'readme',
  'license',
  'licence',
  'changelog',
  'contributing',
  'code_of_conduct',
  'security',
  'authors',
  'copying',
  'notice',
])
